// <auto-generated />
using System;
using System.Collections.Generic;
using Ar_Card_Connect_Api.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ar_Card_Connect_Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422130541_RemoveStatusFromUserCard")]
    partial class RemoveStatusFromUserCard
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ar_Card_Connect_Api.Models.Role", b =>
                {
                    b.Property<Guid>("role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("role_id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Ar_Card_Connect_Api.Models.UserCard", b =>
                {
                    b.Property<Guid>("userCard_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("image_url")
                        .HasColumnType("text");

                    b.Property<bool>("is_blocked")
                        .HasColumnType("boolean");

                    b.Property<string>("marker_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("model_url")
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("position")
                        .HasColumnType("text");

                    b.Property<List<string>>("social_links")
                        .HasColumnType("text[]");

                    b.Property<string>("template")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("userCard_id");

                    b.HasIndex("user_id");

                    b.ToTable("UserCards");
                });

            modelBuilder.Entity("Ar_Card_Connect_Api.Models.UserLogin", b =>
                {
                    b.Property<Guid>("login_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("login_id");

                    b.HasIndex("user_id");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Ar_Card_Connect_Api.Models.UserProfile", b =>
                {
                    b.Property<Guid>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("avatar_url")
                        .HasColumnType("text");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_blocked")
                        .HasColumnType("boolean");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .HasColumnType("text");

                    b.Property<Guid>("role_id")
                        .HasColumnType("uuid");

                    b.Property<string>("surname")
                        .HasColumnType("text");

                    b.HasKey("user_id");

                    b.HasIndex("role_id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Ar_Card_Connect_Api.Models.UserCard", b =>
                {
                    b.HasOne("Ar_Card_Connect_Api.Models.UserProfile", "User")
                        .WithMany("Cards")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ar_Card_Connect_Api.Models.UserLogin", b =>
                {
                    b.HasOne("Ar_Card_Connect_Api.Models.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ar_Card_Connect_Api.Models.UserProfile", b =>
                {
                    b.HasOne("Ar_Card_Connect_Api.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Ar_Card_Connect_Api.Models.UserProfile", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
